<a href="https://colab.research.google.com/github/saidara/sample/blob/main/pattrens.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# patterns in python
patterns are created using for loops, multiple for loops are used to print patterns


1.   outer loop to print number of rows
2.   inner loop to print number of columns 
3.   a variable to print whitespace according to the required place

## pyramid pattern

![image.png]()

In [ ]:
n=int(input("Enter no of rows "))
# outer loop to go through rows
for i in range(0,n):
  # inner loop to handle number of columns
  for j in range(0,i+1):
    # printing star
    print("* ",end="")
    # ending line after each row
  print()

![Mirrored_Triangle_Star_Pattern.png]()

In [ ]:
rows = int(input("Enter no of rows "))
k = 2*rows - 2
for i in range(0,rows):
  for j in range(0,k):
    print(end=" ")
  k=k-2
  for j in range(0,i+1):
    print("* ",end="")
  print()

Enter no of rows 7
            *
          * *
        * * *
      * * * *
    * * * * *
  * * * * * *
* * * * * * *

In [ ]:
rows = int(input("enter no of rows "))
for i in range(rows+1,0,-1):
  for j in range(0,i-1):
    print("* ",end="")
  print(" ")

enter no of rows 5
* * * * *
* * * *
* * *
* *
*

In [ ]:
rows = int(input("Enter no of rows "))
k= 2*rows-2
for i in range(0,rows):
  for j in range(0,k):
    print(end=" ")
  k=k-1
  for j in range(0,i+1):
    print("* ",end='')
  print(" ")

Enter no of rows 5
        *
       * *
      * * *
     * * * *
    * * * * *

In [ ]:
rows=int(input("Enter no of rows "))
k=2*rows-2
for i in range(rows,-1,-1):
  for j in range(k,0,-1):
    print(end=" ")
  k=k+1
  for j in range(0,i+1):
    print("* ",end="")
  print(" ")

Enter no of rows 5
        * * * * * *
         * * * * *
          * * * *
           * * *
            * *
             *

In [ ]:
rows= int(input("Enter no of rows "))
k=2*rows-2
for i in range(0,rows+1):
  for j in range(0,k):
    print(end=" ")
  k=k-1
  for j in range(0,i+1):
    print("* ",end="")
  print(" ")
k=rows-2
for i in range(rows,-1,-1):
  for j in range(k+1,0,-1):
    print(end=" ")
  k=k+1
  for j in range(0,i):
    print("* ",end="")
  print(" ")

Enter no of rows 4
      *
     * *
    * * *
   * * * *
  * * * * *
   * * * *
    * * *
     * *
      *

In [ ]:
rows=int(input("enter no of rows "))
for i in range(0,rows):
  for j in range(0,i+1):
    print("* ",end="")
  print(" ")
for i in range(rows,0,-1):
  for j in range(0,i):
    print("* ",end="")
  print(" ")

enter no of rows 5
*
* *
* * *
* * * *
* * * * *
* * * * *
* * * *
* * *
* *
*

In [ ]:
rows=int(input("enter no of rows "))
k=2*rows-2
for i in range(rows,-1,-1):
  for j in range(k,0,-1):
    print(end=" ")
  k=k+1
  for j in range(0,i+1):
    print("* ",end="")
  print(" ")
k=3*rows-2
for i in range(0,rows+1):
  for j in range(0,k):
    print(end=" ")
  k=k-1
  for j in range(0,i+1):
    print("* ",end="")
  print(" ")

enter no of rows 5
        * * * * * *
         * * * * *
          * * * *
           * * *
            * *
             *
             *
            * *
           * * *
          * * * *
         * * * * *
        * * * * * *

In [ ]:
rows=int(input("Enter no of rows "))
for i in range(0,rows):
  for j in range(0,i+1):
    print(i+1,end=" ")
  print(" ")

Enter no of rows 5
1
2 2
3 3 3
4 4 4 4
5 5 5 5 5

In [ ]:
rows=int(input("Enter no of rows "))
for i in range(0,rows):
  for j in range(0,i+1):
    print(j+1,end=" ")
  print(" ")

Enter no of rows 5
1
1 2
1 2 3
1 2 3 4
1 2 3 4 5

In [ ]:
rows=int(input("Enter no of rows "))
for i in range(rows,0,-1):
  for j in range(0,i):
    print(rows+1-i,end=" ")
  print(" ")

Enter no of rows 5
1 1 1 1 1
2 2 2 2
3 3 3
4 4
5

In [ ]:
rows=int(input("Enter no of rows "))
for i in range(rows,0,-1):
  for j in range(0,i):
    print(rows,end=" ")
  print(" ")

Enter no of rows 6
6 6 6 6 6 6
6 6 6 6 6
6 6 6 6
6 6 6
6 6
6

In [ ]:
rows=int(input("Enter no of rows "))
for i in range(rows,0,-1):
  for j in range(0,i):
    print(i,end=" ")
  print(" ")

Enter no of rows 6
6 6 6 6 6 6
5 5 5 5 5
4 4 4 4
3 3 3
2 2
1

In [ ]:
rows=int(input("enter no of rows "))
current_num=1
stop=2
for i in range(rows):
  for j in range(1,stop):
    print(current_num,end=" ")
    current_num+=1
  print(" ")
  stop+=2

enter no of rows 3
1
2 3 4
5 6 7 8 9

In [ ]:
rows=int(input("Enter no of rows "))
for i in range(rows,0,-1):
  for j in range(0,i):
    print(i-j,end=" ")
  print(" ")

Enter no of rows 8
8 7 6 5 4 3 2 1
7 6 5 4 3 2 1
6 5 4 3 2 1
5 4 3 2 1
4 3 2 1
3 2 1
2 1
1

In [ ]:
rows=int(input("Enter no of rows "))
for i in range(1,rows+1):
  for j in range(1,i+1):
    print(i*2-1,end=" ")
  print(" ")

Enter no of rows 5
1
3 3
5 5 5
7 7 7 7
9 9 9 9 9

In [ ]:
rows=int(input("Enter no of rows "))
for i in range(1,rows+1):
  for j in range(1,rows+1):
    if j<=i:
      print(i,end=" ")
    else:
      print(j,end=" ")
  print(" ")

Enter no of rows 5
1 2 3 4 5
2 2 3 4 5
3 3 3 4 5
4 4 4 4 5
5 5 5 5 5

In [ ]:
rows=int(input("Enter no of rows "))
for i in range(1,rows):
  for j in range(1,i+1):
    print(i*j,end=" ")
  print(" ")

Enter no of rows 8
1
2 4
3 6 9
4 8 12 16
5 10 15 20 25
6 12 18 24 30 36
7 14 21 28 35 42 49

In [ ]:
rows=int(input("Enter no of rows "))
asci_value=65
for i in range(0,rows):
  for j in range(0,i+1):
    alphabate=chr(asci_value)
    print(alphabate,end=" ")
    asci_value+=1
  print(" ")

Enter no of rows 8
A
B C
D E F
G H I J
K L M N O
P Q R S T U
V W X Y Z [ \
] ^ _ ` a b c d

In [ ]:
str1="python"
s=""
for i in str1:
  s+=i
  print(s)
print(" ")

p
py
pyt
pyth
pytho
python

In [ ]:
n=6
for row in range(0,n):
  for col in range(0,n+1):
    if ((row==0 and col%3!=0) or (row==1 and col%3==0) or row-col==2 or row+col==8 ):
      print("*",end=" ")
    else:
      print(" ",end=" ")


  print(" ")

  * *   * *
*     *     *
*           *
  *       *
    *   *
      *

In [ ]:
n=int(input("Enter no of rows: "))
for row in range(n):
  val=row+1
  dec=n-1
  for col in range(row+1):
    print(val,end=" ")
    val=val+dec
    dec=dec-1
  print()

Enter no of rows: 5
1
2 6
3 7 10
4 8 11 13
5 9 12 14 15

Enter no of rows: 4
1
2
3
4
17
18
19
20
5
6
7
14
15
16

8
9
12
13


10
11

In [ ]:

rows = int(input("Enter no of rows "))
k = 2*rows - 2
m=1
n=rows*3-1
for i in range(rows,-1,-1):
  for j in range(k,0,-1):
    print(end=" ")
  k=k+2
  for j in range(0,i):
    print(m ,end=" ")
    m=m+1
  for l in range(i,i*2):
    print(n,end=' ')
    n+=1
  print(" ")

Enter no of rows 4
      1 2 3 4 11 12 13 14
        5 6 7 15 16 17
          8 9 18 19
            10 20

In [ ]:
n=int(input("Enter num: "))

def palindrome(n):
  num_str=str(n)
  rev_str=num_str[::-1]
  if num_str==rev_str:
    return True
for i in range(n,1,-1):
  if palindrome(i):
    print("Largest palindrome is ",i)
    break

Enter num: 45
Largest palindrome is  44

In [ ]:

rows = int(input("Enter no of rows "))
for i in range(0,rows):
  for j in range(rows-1,i,-1):
    print(j,'',end='')
  for l in range(i):
    print('    ',end='')
    #print('  ',end='')
  for k in range(i+1,rows):
    print(k,'',end='')
  print('\n')

Enter no of rows 6
5 4 3 2 1 1 2 3 4 5

5 4 3 2     2 3 4 5

5 4 3         3 4 5

5 4             4 5

5                 5